include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
