targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
          any_map: true
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          field_rename: none
          ignore_unannotated: false